global:
  resolve_timeout: 5m

route:
  receiver: 'slack-notifications'
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/XXX/YYY/ZZZ'
        channel: '#alerts'
        send_resolved: true
  - name: 'email-notifications'
    email_configs:
      - to: 'your@email.com'
        from: 'alert@mrmark.com'
        smarthost: 'smtp.yourmail.com:587'
        auth_username: 'alert@mrmark.com'
        auth_password: 'password'
        send_resolved: true 