global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ai-engine'
    static_configs:
      - targets: ['ai-engine:8001']
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8001']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100'] 