version: "3.8"
services:
  frontend:
    build: ./apps/frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
  backend:
    build: ./apps/backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - ENV=development
  ai-engine:
    build: ./apps/ai-engine
    command: uvicorn app:app --host 0.0.0.0 --port 9000 --reload
    ports:
      - "9000:9000"
    environment:
      - ENV=development

