apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ai-engine
spec:
  podSelector:
    matchLabels:
      app: ai-engine
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: backend
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: backend 