apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-engine-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-engine
      version: blue
  template:
    metadata:
      labels:
        app: ai-engine
        version: blue
    spec:
      containers:
      - name: ai-engine
        image: yourrepo/ai-engine:blue
        ports:
        - containerPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-engine-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-engine
      version: green
  template:
    metadata:
      labels:
        app: ai-engine
        version: green
    spec:
      containers:
      - name: ai-engine
        image: yourrepo/ai-engine:green
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: ai-engine-service
spec:
  selector:
    app: ai-engine
    version: blue # green으로 변경 시 트래픽 전환
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001 